import StyleDictionary from 'style-dictionary'
import { formattedVariables } from 'style-dictionary/utils'

const designSystems = ['ds-minimal', 'ds-editorial', 'ds-brutalist']

// Semantic bridge: maps unprefixed vars (used by components) to
// the theme-prefixed vars generated by Style Dictionary.
const commonSemanticBridge = (ds) => `
  /* semantic bridge — consumed by components */
  --color-semantic-background: var(--${ds}-color-semantic-background);
  --color-semantic-foreground: var(--${ds}-color-semantic-foreground);
  --color-semantic-foreground-muted: var(--${ds}-color-semantic-foreground-muted);
  --color-semantic-border: var(--${ds}-color-semantic-border);
  --color-semantic-primary: var(--${ds}-color-semantic-primary);
  --color-semantic-primary-foreground: var(--${ds}-color-semantic-primary-foreground);
  --border-radius-sm: var(--${ds}-border-radius-sm);
  --border-radius-md: var(--${ds}-border-radius-md);
  --border-radius-lg: var(--${ds}-border-radius-lg);
  --border-radius-full: var(--${ds}-border-radius-full);
  --font-family-sans: var(--${ds}-typography-font-family-sans);
  --typography-font-family-sans: var(--${ds}-typography-font-family-sans);
  --typography-font-family-mono: var(--${ds}-typography-font-family-mono, monospace);
  --typography-font-size-xs: var(--${ds}-typography-font-size-xs);
  --typography-font-size-sm: var(--${ds}-typography-font-size-sm);
  --typography-font-size-md: var(--${ds}-typography-font-size-md);
  --typography-font-size-lg: var(--${ds}-typography-font-size-lg);
  --typography-font-size-xl: var(--${ds}-typography-font-size-xl);
  --typography-font-weight-regular: var(--${ds}-typography-font-weight-regular);
  --typography-font-weight-medium: var(--${ds}-typography-font-weight-medium);
  --typography-font-weight-semibold: var(--${ds}-typography-font-weight-semibold, 600);
  --typography-font-weight-bold: var(--${ds}-typography-font-weight-bold);
  --typography-line-height-tight: var(--${ds}-typography-line-height-tight);
  --typography-line-height-normal: var(--${ds}-typography-line-height-normal);
  --typography-line-height-relaxed: var(--${ds}-typography-line-height-relaxed);
  --spacing-0: var(--${ds}-spacing-0);
  --spacing-1: var(--${ds}-spacing-1);
  --spacing-2: var(--${ds}-spacing-2);
  --spacing-3: var(--${ds}-spacing-3);
  --spacing-4: var(--${ds}-spacing-4);
  --spacing-5: var(--${ds}-spacing-5);
  --spacing-6: var(--${ds}-spacing-6);
  --spacing-8: var(--${ds}-spacing-8);`

// Per-DS extras
const extraBridge = {
  'ds-minimal': `
  --color-semantic-background-subtle: var(--ds-minimal-color-semantic-background-subtle);
  --color-semantic-primary-hover: var(--ds-minimal-color-semantic-primary-hover);`,
  'ds-editorial': `
  --color-semantic-highlight: var(--ds-editorial-color-semantic-highlight);`,
  'ds-brutalist': `
  --color-semantic-accent: var(--ds-brutalist-color-semantic-accent);`,
}

// Dark mode overrides per DS
const darkModeTokens = {
  'ds-minimal': {
    'color-semantic-background': '#0a0a0a',
    'color-semantic-background-subtle': '#18181b',
    'color-semantic-foreground': '#fafafa',
    'color-semantic-foreground-muted': '#a1a1aa',
    'color-semantic-border': '#27272a',
    'color-semantic-primary': '#2563eb',
    'color-semantic-primary-foreground': '#ffffff',
    'color-semantic-primary-hover': '#1d4ed8',
  },
  'ds-editorial': {
    'color-semantic-background': '#0f0c08',
    'color-semantic-foreground': '#faf7f2',
    'color-semantic-foreground-muted': '#a89880',
    'color-semantic-border': '#3d3020',
    'color-semantic-primary': '#e05046',
    'color-semantic-primary-foreground': '#0f0c08',
    'color-semantic-highlight': '#d4a017',
  },
  'ds-brutalist': {
    'color-semantic-background': '#000000',
    'color-semantic-foreground': '#ffffff',
    'color-semantic-border': '#ffffff',
    'color-semantic-primary': '#ffe600',
    'color-semantic-primary-foreground': '#000000',
    'color-semantic-accent': '#ff2d00',
  },
}

// Register a custom format that appends the semantic bridge
StyleDictionary.registerFormat({
  name: 'css/variables-with-bridge',
  format: async ({ dictionary, options, file }) => {
    const ds = options.ds
    const selector = options.selector
    const { outputReferences, outputReferenceFallbacks, usesDtcg } = options

    const vars = formattedVariables({
      format: 'css',
      dictionary,
      outputReferences,
      outputReferenceFallbacks,
      usesDtcg,
    })

    const bridge = commonSemanticBridge(ds) + (extraBridge[ds] ?? '')
    const darkTokens = darkModeTokens[ds] ?? {}
    const darkVars = Object.entries(darkTokens)
      .map(([k, v]) => `  --${k}: ${v};`)
      .join('\n')

    return [
      `/**\n * Do not edit directly, this file was auto-generated.\n */\n`,
      `${selector} {\n${vars}\n${bridge}\n}\n`,
      darkVars
        ? `\n${selector}[data-mode="dark"] {\n${darkVars}\n}\n`
        : '',
    ].join('')
  },
})

for (const ds of designSystems) {
  const sd = new StyleDictionary({
    source: [`src/${ds}/*.json`],
    platforms: {
      css: {
        transformGroup: 'css',
        prefix: ds,
        buildPath: `dist/${ds}/`,
        files: [
          {
            destination: 'variables.css',
            format: 'css/variables-with-bridge',
            options: {
              selector: `[data-theme="${ds}"]`,
              outputReferences: true,
              ds,
            },
          },
        ],
      },
      js: {
        transformGroup: 'js',
        buildPath: `dist/${ds}/`,
        files: [
          {
            destination: 'tokens.js',
            format: 'javascript/es6',
          },
        ],
      },
    },
  })

  await sd.buildAllPlatforms()
  console.log(`✅ ${ds} built successfully`)
}
