import StyleDictionary from 'style-dictionary'
import { formattedVariables } from 'style-dictionary/utils'

const designSystems = ['ds-editorial', 'ds-brutalist', 'ds-onyx', 'ds-clean', 'ds-velvet', 'ds-aurum', 'ds-neon', 'ds-nature', 'ds-swiss']

// Semantic bridge: maps unprefixed vars (used by components) to
// the theme-prefixed vars generated by Style Dictionary.
const commonSemanticBridge = (ds) => `
  /* semantic bridge — consumed by components */
  --color-semantic-background: var(--${ds}-color-semantic-background);
  --color-semantic-foreground: var(--${ds}-color-semantic-foreground);
  --color-semantic-foreground-muted: var(--${ds}-color-semantic-foreground-muted);
  --color-semantic-border: var(--${ds}-color-semantic-border);
  --color-semantic-primary: var(--${ds}-color-semantic-primary);
  --color-semantic-primary-foreground: var(--${ds}-color-semantic-primary-foreground);
  --border-radius-sm: var(--${ds}-border-radius-sm);
  --border-radius-md: var(--${ds}-border-radius-md);
  --border-radius-lg: var(--${ds}-border-radius-lg);
  --border-radius-full: var(--${ds}-border-radius-full);
  --font-family-sans: var(--${ds}-typography-font-family-sans);
  --typography-font-family-sans: var(--${ds}-typography-font-family-sans);
  --typography-font-family-mono: var(--${ds}-typography-font-family-mono, monospace);
  --typography-font-size-xs: var(--${ds}-typography-font-size-xs);
  --typography-font-size-sm: var(--${ds}-typography-font-size-sm);
  --typography-font-size-md: var(--${ds}-typography-font-size-md);
  --typography-font-size-lg: var(--${ds}-typography-font-size-lg);
  --typography-font-size-xl: var(--${ds}-typography-font-size-xl);
  --typography-font-weight-regular: var(--${ds}-typography-font-weight-regular);
  --typography-font-weight-medium: var(--${ds}-typography-font-weight-medium);
  --typography-font-weight-semibold: var(--${ds}-typography-font-weight-semibold, 600);
  --typography-font-weight-bold: var(--${ds}-typography-font-weight-bold);
  --typography-line-height-tight: var(--${ds}-typography-line-height-tight);
  --typography-line-height-normal: var(--${ds}-typography-line-height-normal);
  --typography-line-height-relaxed: var(--${ds}-typography-line-height-relaxed);
  --spacing-0: var(--${ds}-spacing-0);
  --spacing-1: var(--${ds}-spacing-1);
  --spacing-2: var(--${ds}-spacing-2);
  --spacing-3: var(--${ds}-spacing-3);
  --spacing-4: var(--${ds}-spacing-4);
  --spacing-5: var(--${ds}-spacing-5);
  --spacing-6: var(--${ds}-spacing-6);
  --spacing-8: var(--${ds}-spacing-8);
  --color-state-success: var(--${ds}-color-state-success);
  --color-state-success-subtle: var(--${ds}-color-state-success-subtle);
  --color-state-success-foreground: var(--${ds}-color-state-success-foreground);
  --color-state-warning: var(--${ds}-color-state-warning);
  --color-state-warning-subtle: var(--${ds}-color-state-warning-subtle);
  --color-state-warning-foreground: var(--${ds}-color-state-warning-foreground);
  --color-state-error: var(--${ds}-color-state-error);
  --color-state-error-subtle: var(--${ds}-color-state-error-subtle);
  --color-state-error-foreground: var(--${ds}-color-state-error-foreground);
  --color-state-info: var(--${ds}-color-state-info);
  --color-state-info-subtle: var(--${ds}-color-state-info-subtle);
  --color-state-info-foreground: var(--${ds}-color-state-info-foreground);
  --shadow-none: var(--${ds}-shadow-none);
  --shadow-sm: var(--${ds}-shadow-sm);
  --shadow-md: var(--${ds}-shadow-md);
  --shadow-lg: var(--${ds}-shadow-lg);
  --shadow-xl: var(--${ds}-shadow-xl);
  --transition-fast: var(--${ds}-transition-fast);
  --transition-base: var(--${ds}-transition-base);
  --transition-slow: var(--${ds}-transition-slow);
  --easing-default: var(--${ds}-easing-default);
  --easing-in: var(--${ds}-easing-in);
  --easing-out: var(--${ds}-easing-out);
  --easing-spring: var(--${ds}-easing-spring);`

// Per-DS extras
const extraBridge = {
  'ds-editorial': `
  --color-semantic-background-subtle: var(--ds-editorial-color-semantic-background);
  --color-semantic-highlight: var(--ds-editorial-color-semantic-highlight);
  --color-semantic-primary-hover: var(--ds-editorial-color-semantic-primary);`,
  'ds-brutalist': `
  --color-semantic-background-subtle: var(--ds-brutalist-color-semantic-background);
  --color-semantic-accent: var(--ds-brutalist-color-semantic-accent);
  --color-semantic-foreground-muted: var(--ds-brutalist-color-semantic-foreground);
  --color-semantic-primary-hover: var(--ds-brutalist-color-semantic-primary);`,
  'ds-onyx': `
  --color-semantic-background-subtle: var(--ds-onyx-color-semantic-background-subtle);
  --color-semantic-primary-hover: var(--ds-onyx-color-semantic-primary-hover);
  --font-family-mono: var(--ds-onyx-typography-font-family-mono);`,
  'ds-clean': `
  --color-semantic-background-subtle: var(--ds-clean-color-semantic-background-subtle);
  --color-semantic-primary-hover: var(--ds-clean-color-semantic-primary-hover);
  --font-family-mono: var(--ds-clean-typography-font-family-mono);`,
  'ds-velvet': `
  --color-semantic-background-subtle: var(--ds-velvet-color-semantic-background-subtle);
  --color-semantic-primary-hover: var(--ds-velvet-color-semantic-primary-hover);`,
  'ds-aurum': `
  --color-semantic-background-subtle: var(--ds-aurum-color-semantic-background-subtle);
  --color-semantic-primary-hover: var(--ds-aurum-color-semantic-primary-hover);`,
  'ds-neon': `
  --color-semantic-background-subtle: var(--ds-neon-color-semantic-background-subtle);
  --color-semantic-primary-hover: var(--ds-neon-color-semantic-primary-hover);
  --font-family-mono: var(--ds-neon-typography-font-family-mono);`,
  'ds-nature': `
  --color-semantic-background-subtle: var(--ds-nature-color-semantic-background-subtle);
  --color-semantic-primary-hover: var(--ds-nature-color-semantic-primary-hover);`,
  'ds-swiss': `
  --color-semantic-background-subtle: var(--ds-swiss-color-semantic-background-subtle);
  --color-semantic-primary-hover: var(--ds-swiss-color-semantic-primary-hover);`,
}

// Dark mode overrides per DS
// Contrast ratios verified against WCAG AA (4.5:1 for text, 3:1 for UI elements)
const darkModeTokens = {
  'ds-editorial': {
    // backgrounds — very dark warm tone
    'color-semantic-background':        '#0f0c08',
    'color-semantic-background-subtle': '#1c1610',
    // text — #faf7f2 on #0f0c08 ≈ 18.4:1 ✅; muted #b8a890 ≈ 8.3:1 ✅
    'color-semantic-foreground':        '#faf7f2',
    'color-semantic-foreground-muted':  '#b8a890',
    // border — #5a4a36 on #0f0c08 ≈ 3.4:1 ✅ (UI element)
    'color-semantic-border':            '#5a4a36',
    // primary — #e8675d on #0f0c08 ≈ 5.2:1 ✅; foreground black on red ≈ 4.0:1
    'color-semantic-primary':           '#e8675d',
    'color-semantic-primary-foreground':'#faf7f2',
    'color-semantic-primary-hover':     '#f07d73',
    // highlight gold — #d4a017 on #0f0c08 ≈ 7.7:1 ✅
    'color-semantic-highlight':         '#d4a017',
    // state tokens — warm/muted palette adjusted for dark bg
    'color-state-success':              '#6dbd6d',
    'color-state-success-subtle':       '#0d1f0d',
    'color-state-success-foreground':   '#0f0c08',
    'color-state-warning':              '#d4a017',
    'color-state-warning-subtle':       '#1f1608',
    'color-state-warning-foreground':   '#0f0c08',
    'color-state-error':                '#e8675d',
    'color-state-error-subtle':         '#1f0d0b',
    'color-state-error-foreground':     '#faf7f2',
    'color-state-info':                 '#7aaddb',
    'color-state-info-subtle':          '#0b1520',
    'color-state-info-foreground':      '#0f0c08',
  },
  'ds-brutalist': {
    // backgrounds — pure black / near-black
    'color-semantic-background':        '#000000',
    'color-semantic-background-subtle': '#111111',
    // text — white on black 21:1 ✅; muted #cccccc ≈ 12.6:1 ✅
    'color-semantic-foreground':        '#ffffff',
    'color-semantic-foreground-muted':  '#cccccc',
    // border — white on black 21:1 ✅
    'color-semantic-border':            '#ffffff',
    // primary — yellow on black 17:1 ✅; foreground black on yellow 17:1 ✅
    'color-semantic-primary':           '#ffe600',
    'color-semantic-primary-foreground':'#000000',
    'color-semantic-primary-hover':     '#ffed4a',
    // accent — red on black ≈ 5.7:1 ✅
    'color-semantic-accent':            '#ff2d00',
    // state tokens — keep high-vis neon palette consistent with brutalist style
    'color-state-success':              '#00ff41',
    'color-state-success-subtle':       '#001a0d',
    'color-state-success-foreground':   '#000000',
    'color-state-warning':              '#ffff00',
    'color-state-warning-subtle':       '#1a1a00',
    'color-state-warning-foreground':   '#000000',
    'color-state-error':                '#ff4444',
    'color-state-error-subtle':         '#1a0000',
    'color-state-error-foreground':     '#ffffff',
    'color-state-info':                 '#4da6ff',
    'color-state-info-subtle':          '#00091a',
    'color-state-info-foreground':      '#000000',
  },
  // ds-onyx — dark-first; dark mode = same as base (already dark), violet accent
  'ds-onyx': {
    'color-semantic-background':        '#111113',
    'color-semantic-background-subtle': '#17171a',
    'color-semantic-foreground':        '#efefef',
    'color-semantic-foreground-muted':  '#9a9aa8',
    'color-semantic-border':            'rgba(255,255,255,0.07)',
    'color-semantic-primary':           '#7c6aff',
    'color-semantic-primary-foreground':'#ffffff',
    'color-semantic-primary-hover':     '#5b47ff',
    'color-state-success':              '#22c67a',
    'color-state-success-subtle':       'rgba(34,198,122,0.12)',
    'color-state-success-foreground':   '#111113',
    'color-state-warning':              '#f5a623',
    'color-state-warning-subtle':       'rgba(245,166,35,0.12)',
    'color-state-warning-foreground':   '#111113',
    'color-state-error':                '#ff6a6a',
    'color-state-error-subtle':         'rgba(255,106,106,0.12)',
    'color-state-error-foreground':     '#ffffff',
    'color-state-info':                 '#22d3ee',
    'color-state-info-subtle':          'rgba(34,211,238,0.12)',
    'color-state-info-foreground':      '#111113',
  },
  // ds-clean — dark mode: dark bg #010816 (near-black) with blue-400 primary
  'ds-clean': {
    'color-semantic-background':        '#010816',
    'color-semantic-background-subtle': '#1e293b',
    'color-semantic-foreground':        '#f7f9fb',
    'color-semantic-foreground-muted':  '#94a3b7',
    'color-semantic-border':            '#1e293b',
    'color-semantic-primary':           '#3b82f5',
    'color-semantic-primary-foreground':'#0f172a',
    'color-semantic-primary-hover':     '#60a5fa',
    'color-state-success':              '#22c55e',
    'color-state-success-subtle':       '#052e16',
    'color-state-success-foreground':   '#010816',
    'color-state-warning':              '#eab308',
    'color-state-warning-subtle':       '#1c1408',
    'color-state-warning-foreground':   '#010816',
    'color-state-error':                '#7f1d1d',
    'color-state-error-subtle':         '#1f0505',
    'color-state-error-foreground':     '#f7f9fb',
    'color-state-info':                 '#3b82f5',
    'color-state-info-subtle':          '#030d1f',
    'color-state-info-foreground':      '#010816',
  },
  // ds-aurum — dark mode: deeper navy, brighter gold
  'ds-aurum': {
    'color-semantic-background':        '#060b16',
    'color-semantic-background-subtle': '#0e1629',
    'color-semantic-foreground':        '#f5f0e8',
    'color-semantic-foreground-muted':  '#9a8f7e',
    'color-semantic-border':            '#1e2d4a',
    'color-semantic-primary':           '#dbb95e',
    'color-semantic-primary-foreground':'#060b16',
    'color-semantic-primary-hover':     '#e8ca7a',
    'color-state-success':              '#4caf7d',
    'color-state-success-subtle':       'rgba(76,175,125,0.15)',
    'color-state-success-foreground':   '#060b16',
    'color-state-warning':              '#f5a623',
    'color-state-warning-subtle':       'rgba(245,166,35,0.15)',
    'color-state-warning-foreground':   '#060b16',
    'color-state-error':                '#e05555',
    'color-state-error-subtle':         'rgba(224,85,85,0.15)',
    'color-state-error-foreground':     '#f5f0e8',
    'color-state-info':                 '#5b9bd5',
    'color-state-info-subtle':          'rgba(91,155,213,0.15)',
    'color-state-info-foreground':      '#060b16',
  },
  // ds-neon — already dark; dark mode same with slightly brighter glow
  'ds-neon': {
    'color-semantic-background':        '#080810',
    'color-semantic-background-subtle': '#0f0f1e',
    'color-semantic-foreground':        '#f0f0ff',
    'color-semantic-foreground-muted':  '#9999cc',
    'color-semantic-border':            'rgba(255,0,204,0.2)',
    'color-semantic-primary':           '#ff33dd',
    'color-semantic-primary-foreground':'#ffffff',
    'color-semantic-primary-hover':     '#ff66ee',
    'color-state-success':              '#00ff88',
    'color-state-success-subtle':       'rgba(0,255,136,0.15)',
    'color-state-success-foreground':   '#080810',
    'color-state-warning':              '#ffcc00',
    'color-state-warning-subtle':       'rgba(255,204,0,0.15)',
    'color-state-warning-foreground':   '#080810',
    'color-state-error':                '#ff4444',
    'color-state-error-subtle':         'rgba(255,68,68,0.15)',
    'color-state-error-foreground':     '#ffffff',
    'color-state-info':                 '#00ccff',
    'color-state-info-subtle':          'rgba(0,204,255,0.15)',
    'color-state-info-foreground':      '#080810',
  },
  // ds-nature — dark mode: deep forest
  'ds-nature': {
    'color-semantic-background':        '#1a211a',
    'color-semantic-background-subtle': '#222b22',
    'color-semantic-foreground':        '#e8f0e8',
    'color-semantic-foreground-muted':  '#8aa48a',
    'color-semantic-border':            '#2e3d2e',
    'color-semantic-primary':           '#7aaa7a',
    'color-semantic-primary-foreground':'#1a211a',
    'color-semantic-primary-hover':     '#8fc08f',
    'color-state-success':              '#5aaa75',
    'color-state-success-subtle':       'rgba(90,170,117,0.15)',
    'color-state-success-foreground':   '#1a211a',
    'color-state-warning':              '#d4943a',
    'color-state-warning-subtle':       'rgba(212,148,58,0.15)',
    'color-state-warning-foreground':   '#1a211a',
    'color-state-error':                '#c0503a',
    'color-state-error-subtle':         'rgba(192,80,58,0.15)',
    'color-state-error-foreground':     '#e8f0e8',
    'color-state-info':                 '#5a80bb',
    'color-state-info-subtle':          'rgba(90,128,187,0.15)',
    'color-state-info-foreground':      '#1a211a',
  },
  // ds-swiss — dark mode: inverted (dark bg, white text, white primary)
  'ds-swiss': {
    'color-semantic-background':        '#0a0a0a',
    'color-semantic-background-subtle': '#1a1a1a',
    'color-semantic-foreground':        '#f0f0f0',
    'color-semantic-foreground-muted':  '#aaaaaa',
    'color-semantic-border':            '#333333',
    'color-semantic-primary':           '#ffffff',
    'color-semantic-primary-foreground':'#000000',
    'color-semantic-primary-hover':     '#cccccc',
    'color-state-success':              '#44cc44',
    'color-state-success-subtle':       '#0f1f0f',
    'color-state-success-foreground':   '#0a0a0a',
    'color-state-warning':              '#ccaa00',
    'color-state-warning-subtle':       '#1f1a00',
    'color-state-warning-foreground':   '#0a0a0a',
    'color-state-error':                '#ee2222',
    'color-state-error-subtle':         '#1f0505',
    'color-state-error-foreground':     '#f0f0f0',
    'color-state-info':                 '#4488ee',
    'color-state-info-subtle':          '#050f1f',
    'color-state-info-foreground':      '#0a0a0a',
  },
  // ds-velvet — dark mode: deep dark #0a0a0f + purple-400 accent
  'ds-velvet': {
    'color-semantic-background':        '#0a0a0f',
    'color-semantic-background-subtle': '#16151f',
    'color-semantic-foreground':        '#f0f0f5',
    'color-semantic-foreground-muted':  'rgba(240,240,245,0.45)',
    'color-semantic-border':            'rgba(255,255,255,0.08)',
    'color-semantic-primary':           '#7c6af7',
    'color-semantic-primary-foreground':'#ffffff',
    'color-semantic-primary-hover':     '#6c5ce7',
    'color-state-success':              '#34d399',
    'color-state-success-subtle':       'rgba(52,211,153,0.15)',
    'color-state-success-foreground':   '#0a0a0f',
    'color-state-warning':              '#fbbf24',
    'color-state-warning-subtle':       'rgba(251,191,36,0.12)',
    'color-state-warning-foreground':   '#0a0a0f',
    'color-state-error':                '#f87171',
    'color-state-error-subtle':         'rgba(248,113,113,0.15)',
    'color-state-error-foreground':     '#ffffff',
    'color-state-info':                 '#7c6af7',
    'color-state-info-subtle':          'rgba(124,106,247,0.18)',
    'color-state-info-foreground':      '#0a0a0f',
  },
}

// Register a custom format that appends the semantic bridge
StyleDictionary.registerFormat({
  name: 'css/variables-with-bridge',
  format: async ({ dictionary, options, file }) => {
    const ds = options.ds
    const selector = options.selector
    const { outputReferences, outputReferenceFallbacks, usesDtcg } = options

    const vars = formattedVariables({
      format: 'css',
      dictionary,
      outputReferences,
      outputReferenceFallbacks,
      usesDtcg,
    })

    const bridge = commonSemanticBridge(ds) + (extraBridge[ds] ?? '')
    const darkTokens = darkModeTokens[ds] ?? {}
    const darkVars = Object.entries(darkTokens)
      .map(([k, v]) => `  --${k}: ${v};`)
      .join('\n')

    return [
      `/**\n * Do not edit directly, this file was auto-generated.\n */\n`,
      `${selector} {\n${vars}\n${bridge}\n}\n`,
      darkVars
        ? `\n${selector}[data-mode="dark"] {\n${darkVars}\n}\n`
        : '',
    ].join('')
  },
})

for (const ds of designSystems) {
  const sd = new StyleDictionary({
    source: [`src/${ds}/*.json`],
    platforms: {
      css: {
        transformGroup: 'css',
        prefix: ds,
        buildPath: `dist/${ds}/`,
        files: [
          {
            destination: 'variables.css',
            format: 'css/variables-with-bridge',
            options: {
              selector: `[data-theme="${ds}"]`,
              outputReferences: true,
              ds,
            },
          },
        ],
      },
      js: {
        transformGroup: 'js',
        buildPath: `dist/${ds}/`,
        files: [
          {
            destination: 'tokens.js',
            format: 'javascript/es6',
          },
        ],
      },
    },
  })

  await sd.buildAllPlatforms()
  console.log(`✅ ${ds} built successfully`)
}
