import StyleDictionary from 'style-dictionary'
import { formattedVariables } from 'style-dictionary/utils'

const designSystems = ['ds-minimal', 'ds-editorial', 'ds-brutalist', 'ds-icc', 'ds-dil', 'ds-financas']

// Semantic bridge: maps unprefixed vars (used by components) to
// the theme-prefixed vars generated by Style Dictionary.
const commonSemanticBridge = (ds) => `
  /* semantic bridge — consumed by components */
  --color-semantic-background: var(--${ds}-color-semantic-background);
  --color-semantic-foreground: var(--${ds}-color-semantic-foreground);
  --color-semantic-foreground-muted: var(--${ds}-color-semantic-foreground-muted);
  --color-semantic-border: var(--${ds}-color-semantic-border);
  --color-semantic-primary: var(--${ds}-color-semantic-primary);
  --color-semantic-primary-foreground: var(--${ds}-color-semantic-primary-foreground);
  --border-radius-sm: var(--${ds}-border-radius-sm);
  --border-radius-md: var(--${ds}-border-radius-md);
  --border-radius-lg: var(--${ds}-border-radius-lg);
  --border-radius-full: var(--${ds}-border-radius-full);
  --font-family-sans: var(--${ds}-typography-font-family-sans);
  --typography-font-family-sans: var(--${ds}-typography-font-family-sans);
  --typography-font-family-mono: var(--${ds}-typography-font-family-mono, monospace);
  --typography-font-size-xs: var(--${ds}-typography-font-size-xs);
  --typography-font-size-sm: var(--${ds}-typography-font-size-sm);
  --typography-font-size-md: var(--${ds}-typography-font-size-md);
  --typography-font-size-lg: var(--${ds}-typography-font-size-lg);
  --typography-font-size-xl: var(--${ds}-typography-font-size-xl);
  --typography-font-weight-regular: var(--${ds}-typography-font-weight-regular);
  --typography-font-weight-medium: var(--${ds}-typography-font-weight-medium);
  --typography-font-weight-semibold: var(--${ds}-typography-font-weight-semibold, 600);
  --typography-font-weight-bold: var(--${ds}-typography-font-weight-bold);
  --typography-line-height-tight: var(--${ds}-typography-line-height-tight);
  --typography-line-height-normal: var(--${ds}-typography-line-height-normal);
  --typography-line-height-relaxed: var(--${ds}-typography-line-height-relaxed);
  --spacing-0: var(--${ds}-spacing-0);
  --spacing-1: var(--${ds}-spacing-1);
  --spacing-2: var(--${ds}-spacing-2);
  --spacing-3: var(--${ds}-spacing-3);
  --spacing-4: var(--${ds}-spacing-4);
  --spacing-5: var(--${ds}-spacing-5);
  --spacing-6: var(--${ds}-spacing-6);
  --spacing-8: var(--${ds}-spacing-8);
  --color-state-success: var(--${ds}-color-state-success);
  --color-state-success-subtle: var(--${ds}-color-state-success-subtle);
  --color-state-success-foreground: var(--${ds}-color-state-success-foreground);
  --color-state-warning: var(--${ds}-color-state-warning);
  --color-state-warning-subtle: var(--${ds}-color-state-warning-subtle);
  --color-state-warning-foreground: var(--${ds}-color-state-warning-foreground);
  --color-state-error: var(--${ds}-color-state-error);
  --color-state-error-subtle: var(--${ds}-color-state-error-subtle);
  --color-state-error-foreground: var(--${ds}-color-state-error-foreground);
  --color-state-info: var(--${ds}-color-state-info);
  --color-state-info-subtle: var(--${ds}-color-state-info-subtle);
  --color-state-info-foreground: var(--${ds}-color-state-info-foreground);
  --shadow-none: var(--${ds}-shadow-none);
  --shadow-sm: var(--${ds}-shadow-sm);
  --shadow-md: var(--${ds}-shadow-md);
  --shadow-lg: var(--${ds}-shadow-lg);
  --shadow-xl: var(--${ds}-shadow-xl);
  --transition-fast: var(--${ds}-transition-fast);
  --transition-base: var(--${ds}-transition-base);
  --transition-slow: var(--${ds}-transition-slow);
  --easing-default: var(--${ds}-easing-default);
  --easing-in: var(--${ds}-easing-in);
  --easing-out: var(--${ds}-easing-out);
  --easing-spring: var(--${ds}-easing-spring);`

// Per-DS extras
const extraBridge = {
  'ds-minimal': `
  --color-semantic-background-subtle: var(--ds-minimal-color-semantic-background-subtle);
  --color-semantic-primary-hover: var(--ds-minimal-color-semantic-primary-hover);`,
  'ds-editorial': `
  --color-semantic-background-subtle: var(--ds-editorial-color-semantic-background);
  --color-semantic-highlight: var(--ds-editorial-color-semantic-highlight);
  --color-semantic-primary-hover: var(--ds-editorial-color-semantic-primary);`,
  'ds-brutalist': `
  --color-semantic-background-subtle: var(--ds-brutalist-color-semantic-background);
  --color-semantic-accent: var(--ds-brutalist-color-semantic-accent);
  --color-semantic-foreground-muted: var(--ds-brutalist-color-semantic-foreground);
  --color-semantic-primary-hover: var(--ds-brutalist-color-semantic-primary);`,
  'ds-icc': `
  --color-semantic-background-subtle: var(--ds-icc-color-semantic-background-subtle);
  --color-semantic-primary-hover: var(--ds-icc-color-semantic-primary-hover);
  --font-family-mono: var(--ds-icc-typography-font-family-mono);`,
  'ds-dil': `
  --color-semantic-background-subtle: var(--ds-dil-color-semantic-background-subtle);
  --color-semantic-primary-hover: var(--ds-dil-color-semantic-primary-hover);
  --font-family-mono: var(--ds-dil-typography-font-family-mono);`,
  'ds-financas': `
  --color-semantic-background-subtle: var(--ds-financas-color-semantic-background-subtle);
  --color-semantic-primary-hover: var(--ds-financas-color-semantic-primary-hover);`,
}

// Dark mode overrides per DS
// Contrast ratios verified against WCAG AA (4.5:1 for text, 3:1 for UI elements)
const darkModeTokens = {
  'ds-minimal': {
    // backgrounds
    'color-semantic-background':        '#0a0a0a',
    'color-semantic-background-subtle': '#18181b',
    // text — foreground #fafafa on #0a0a0a ≈ 18.6:1 ✅; muted #a1a1aa ≈ 7.0:1 ✅
    'color-semantic-foreground':        '#fafafa',
    'color-semantic-foreground-muted':  '#a1a1aa',
    // border — #3f3f46 on #0a0a0a ≈ 3.3:1 ✅ (UI element)
    'color-semantic-border':            '#3f3f46',
    // primary — #60a5fa on #0a0a0a ≈ 6.5:1 ✅ (brighter blue for dark bg)
    'color-semantic-primary':           '#60a5fa',
    'color-semantic-primary-foreground':'#0a0a0a',
    'color-semantic-primary-hover':     '#93c5fd',
    // state tokens — boosted for dark bg readability
    'color-state-success':              '#4ade80',
    'color-state-success-subtle':       '#052e16',
    'color-state-success-foreground':   '#0a0a0a',
    'color-state-warning':              '#fbbf24',
    'color-state-warning-subtle':       '#1c1408',
    'color-state-warning-foreground':   '#0a0a0a',
    'color-state-error':                '#f87171',
    'color-state-error-subtle':         '#1f0505',
    'color-state-error-foreground':     '#0a0a0a',
    'color-state-info':                 '#60a5fa',
    'color-state-info-subtle':          '#030d1f',
    'color-state-info-foreground':      '#0a0a0a',
  },
  'ds-editorial': {
    // backgrounds — very dark warm tone
    'color-semantic-background':        '#0f0c08',
    'color-semantic-background-subtle': '#1c1610',
    // text — #faf7f2 on #0f0c08 ≈ 18.4:1 ✅; muted #b8a890 ≈ 8.3:1 ✅
    'color-semantic-foreground':        '#faf7f2',
    'color-semantic-foreground-muted':  '#b8a890',
    // border — #5a4a36 on #0f0c08 ≈ 3.4:1 ✅ (UI element)
    'color-semantic-border':            '#5a4a36',
    // primary — #e8675d on #0f0c08 ≈ 5.2:1 ✅; foreground black on red ≈ 4.0:1
    'color-semantic-primary':           '#e8675d',
    'color-semantic-primary-foreground':'#faf7f2',
    'color-semantic-primary-hover':     '#f07d73',
    // highlight gold — #d4a017 on #0f0c08 ≈ 7.7:1 ✅
    'color-semantic-highlight':         '#d4a017',
    // state tokens — warm/muted palette adjusted for dark bg
    'color-state-success':              '#6dbd6d',
    'color-state-success-subtle':       '#0d1f0d',
    'color-state-success-foreground':   '#0f0c08',
    'color-state-warning':              '#d4a017',
    'color-state-warning-subtle':       '#1f1608',
    'color-state-warning-foreground':   '#0f0c08',
    'color-state-error':                '#e8675d',
    'color-state-error-subtle':         '#1f0d0b',
    'color-state-error-foreground':     '#faf7f2',
    'color-state-info':                 '#7aaddb',
    'color-state-info-subtle':          '#0b1520',
    'color-state-info-foreground':      '#0f0c08',
  },
  'ds-brutalist': {
    // backgrounds — pure black / near-black
    'color-semantic-background':        '#000000',
    'color-semantic-background-subtle': '#111111',
    // text — white on black 21:1 ✅; muted #cccccc ≈ 12.6:1 ✅
    'color-semantic-foreground':        '#ffffff',
    'color-semantic-foreground-muted':  '#cccccc',
    // border — white on black 21:1 ✅
    'color-semantic-border':            '#ffffff',
    // primary — yellow on black 17:1 ✅; foreground black on yellow 17:1 ✅
    'color-semantic-primary':           '#ffe600',
    'color-semantic-primary-foreground':'#000000',
    'color-semantic-primary-hover':     '#ffed4a',
    // accent — red on black ≈ 5.7:1 ✅
    'color-semantic-accent':            '#ff2d00',
    // state tokens — keep high-vis neon palette consistent with brutalist style
    'color-state-success':              '#00ff41',
    'color-state-success-subtle':       '#001a0d',
    'color-state-success-foreground':   '#000000',
    'color-state-warning':              '#ffff00',
    'color-state-warning-subtle':       '#1a1a00',
    'color-state-warning-foreground':   '#000000',
    'color-state-error':                '#ff4444',
    'color-state-error-subtle':         '#1a0000',
    'color-state-error-foreground':     '#ffffff',
    'color-state-info':                 '#4da6ff',
    'color-state-info-subtle':          '#00091a',
    'color-state-info-foreground':      '#000000',
  },
  // ds-icc — dark-first; dark mode = same as base (already dark), violet accent
  'ds-icc': {
    'color-semantic-background':        '#020617',
    'color-semantic-background-subtle': '#0f172a',
    'color-semantic-foreground':        '#f1f5f9',
    'color-semantic-foreground-muted':  '#94a3b8',
    'color-semantic-border':            '#334155',
    'color-semantic-primary':           '#a78bfa',
    'color-semantic-primary-foreground':'#020617',
    'color-semantic-primary-hover':     '#c4b5fd',
    'color-state-success':              '#4ade80',
    'color-state-success-subtle':       '#052e16',
    'color-state-success-foreground':   '#020617',
    'color-state-warning':              '#fbbf24',
    'color-state-warning-subtle':       '#1c1408',
    'color-state-warning-foreground':   '#020617',
    'color-state-error':                '#f87171',
    'color-state-error-subtle':         '#1f0505',
    'color-state-error-foreground':     '#f8fafc',
    'color-state-info':                 '#818cf8',
    'color-state-info-subtle':          '#030d1f',
    'color-state-info-foreground':      '#020617',
  },
  // ds-dil — dark mode: deeper dark with brighter indigo
  'ds-dil': {
    'color-semantic-background':        '#0b0f1a',
    'color-semantic-background-subtle': '#111827',
    'color-semantic-foreground':        '#f3f4f6',
    'color-semantic-foreground-muted':  '#9ca3af',
    'color-semantic-border':            '#374151',
    'color-semantic-primary':           '#818cf8',
    'color-semantic-primary-foreground':'#0b0f1a',
    'color-semantic-primary-hover':     '#a5b4fc',
    'color-state-success':              '#4ade80',
    'color-state-success-subtle':       '#052e16',
    'color-state-success-foreground':   '#0b0f1a',
    'color-state-warning':              '#fbbf24',
    'color-state-warning-subtle':       '#1c1408',
    'color-state-warning-foreground':   '#0b0f1a',
    'color-state-error':                '#f87171',
    'color-state-error-subtle':         '#1f0505',
    'color-state-error-foreground':     '#f3f4f6',
    'color-state-info':                 '#60a5fa',
    'color-state-info-subtle':          '#030d1f',
    'color-state-info-foreground':      '#0b0f1a',
  },
  // ds-financas — dark mode: dark bg #16171d + purple-400 accent (from real CSS)
  'ds-financas': {
    'color-semantic-background':        '#16171d',
    'color-semantic-background-subtle': '#1f2028',
    'color-semantic-foreground':        '#f3f4f6',
    'color-semantic-foreground-muted':  '#9ca3af',
    'color-semantic-border':            '#2e303a',
    'color-semantic-primary':           '#c084fc',
    'color-semantic-primary-foreground':'#16171d',
    'color-semantic-primary-hover':     '#d8b4fe',
    'color-state-success':              '#4ade80',
    'color-state-success-subtle':       '#052e16',
    'color-state-success-foreground':   '#16171d',
    'color-state-warning':              '#fbbf24',
    'color-state-warning-subtle':       '#1c1408',
    'color-state-warning-foreground':   '#16171d',
    'color-state-error':                '#f87171',
    'color-state-error-subtle':         '#1f0505',
    'color-state-error-foreground':     '#f3f4f6',
    'color-state-info':                 '#818cf8',
    'color-state-info-subtle':          '#0c0d17',
    'color-state-info-foreground':      '#16171d',
  },
}

// Register a custom format that appends the semantic bridge
StyleDictionary.registerFormat({
  name: 'css/variables-with-bridge',
  format: async ({ dictionary, options, file }) => {
    const ds = options.ds
    const selector = options.selector
    const { outputReferences, outputReferenceFallbacks, usesDtcg } = options

    const vars = formattedVariables({
      format: 'css',
      dictionary,
      outputReferences,
      outputReferenceFallbacks,
      usesDtcg,
    })

    const bridge = commonSemanticBridge(ds) + (extraBridge[ds] ?? '')
    const darkTokens = darkModeTokens[ds] ?? {}
    const darkVars = Object.entries(darkTokens)
      .map(([k, v]) => `  --${k}: ${v};`)
      .join('\n')

    return [
      `/**\n * Do not edit directly, this file was auto-generated.\n */\n`,
      `${selector} {\n${vars}\n${bridge}\n}\n`,
      darkVars
        ? `\n${selector}[data-mode="dark"] {\n${darkVars}\n}\n`
        : '',
    ].join('')
  },
})

for (const ds of designSystems) {
  const sd = new StyleDictionary({
    source: [`src/${ds}/*.json`],
    platforms: {
      css: {
        transformGroup: 'css',
        prefix: ds,
        buildPath: `dist/${ds}/`,
        files: [
          {
            destination: 'variables.css',
            format: 'css/variables-with-bridge',
            options: {
              selector: `[data-theme="${ds}"]`,
              outputReferences: true,
              ds,
            },
          },
        ],
      },
      js: {
        transformGroup: 'js',
        buildPath: `dist/${ds}/`,
        files: [
          {
            destination: 'tokens.js',
            format: 'javascript/es6',
          },
        ],
      },
    },
  })

  await sd.buildAllPlatforms()
  console.log(`✅ ${ds} built successfully`)
}
